title: The yEAh Arcade
description: Play HTML5, Flash, Gameboy, DS and other retro games in your browser, online, unblocked, for free, with zero ads.

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-redirect-from
