name: Deploy to server
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: main # The branch the action should deploy to.
